- rootdir/fstab.loire
> Loire: Fix SDcard1 path

- rootdir/init.loire.pwr.rc
> loire: Remove non-existing cpu tasks

- rootdir/init.loire.rc
maxim is karin's display ...... suzu uses clearpad
> loire: remove maxim path for taptowake

- platform.mk
- rootdir/init.loire.rc
Uim service needed for fm functionality.
> Build FMRadio packages. Add uim service.

- rootdir/init.loire.rc
Also restrict system services to system background cpuset
> Add support for top-app cpuset

- rootdir/init.loire.rc
Following: e23e484bda4ab412c07665b3d8bd7bf2c712b92a
> loire: add init CPUSETS

- rootdir/init.loire.pwr.rc
Config values are taken from stock.
> init: refactor init.loire.pwr.rc

- PlatformConfig.mk
7.1.1_r4 requirement
https://android.googlesource.com/platform/external/libnfc-nci/+/android-7.1.1_r4/halimpl/pn54x/Android.mk#15
Change-Id: I710c7da1e4979637acf24f71a8238c978d3f52cf
> [master] sony: loire: Update NFC chip type config

- PlatformConfig.mk
This reverts commit f41703e94ae027659a8eca97f7dd9e49c4501ab6.
> Revert "sony: loire: Update NFC chip type config"

- rootdir/ueventd.loire.rc
also removed not present dev paths
> loire: ueventd: fix nfc permissions

- rootdir/init.loire.rc
Change-Id: I0003f0ef99acdef64dbe20a6e8a13cff2c4e7bf5
> init: adjust bcmdhd_wlan path

- rootdir/init.loire.rc
This reverts commit a118c876ba6539c5ddbe2280a0b74b3da98782b7.
> Revert "loire: fix macaddr path"

- rootdir/init.loire.rc
> loire: move services to vendor

- rootdir/system/etc/media_codecs.xml
- rootdir/system/etc/media_codecs_performance.xml
- rootdir/system/etc/media_profiles_V1_0.xml
> loire: update media conf files

- rootdir/fstab.loire
- rootdir/init.loire.rc
- sepolicy_platform/file_contexts
- sepolicy_platform/genfs_contexts
To be merged once the new device-sony-sepolicy is complete
> sepolicy improvements

- rootdir/init.loire.rc
Change-Id: I4e3f3f2948fa83d775a72de4fa31ad1022c1a574
> [master] sony: loire: Move fstab mount process to common

- rootdir/init.loire.rc
commonize init stuff
Change-Id: I7fe32ab3b384fd56202c16997f083b76c069684e
> [o-mr0]  sony: loire: init: Move common stuff

- rootdir/init.loire.rc
Move common init stuff between loire, tone and yoshino platforms.
> [master] Move common init stuff

- README.md
> [n-mr1-legacy] README.md: Update Sony Developer World domain

- README.md
> [master] README.md: Add Xperia Touch (blanc)

- rootdir/vendor/etc/fstab.loire
Bug: 30807864
Change-Id: If3f67d5b7b15409c2717ef0d92851ca46677e4ff
> Remove discard in fstab

- rootdir/vendor/etc/fstab.loire
Bug: 38351804
Test: boot
Change-Id: Ibe884310960f88ce7dd757a50b232fc70ae89274
> Add quota support to data partition

- rootdir/vendor/etc/rqbalance_config.xml
Add the configuration for the sustained performance power hint
and update the other configurations to use RQB-CFL where possible
to achieve better performance for app opening and better battery
life in batterysave cases.
> [LOIRE] rqbalance_config: Update configuration for RQB-CFL and sustained

- rootdir/vendor/etc/init/init.loire.pwr.rc
the same driver same paths are used by all platforms move it to common repo
> PowerHal: move all needed perm to common

- PlatformConfig.mk
this was reworked in fpc hal in commit ee01f1e19c3a192430d5376d8ac01e4cfd214c50
> remove not needed FPC flag
