rootdir/init.recovery.loire.rc

Following: https://github.com/sonyxperiadev/device-sony-loire/blob/master/rootdir/init.loire.rc#L20

Loire: fix init.recovery.rc

---

PlatformConfig.mk
rootdir/init.loire.pwr.rc
rootdir/ueventd.loire.rc
system.prop

Core limiting via msm_performance works well, but cpuquiet absolutely
hates it. rqbalance is not aware of msm_performance so it spams dmesg
because it cannot online a core for 'unknown' reasons.
We can achieve the same result using cpuquiet which rqbalance is
aware of. We can also have two sources of core limiting, power
profile and thermal.
We also need to tune rqbalance and cpuquiet per platform so also
move their system props.

Move sysfs and props for cpuquiet hotplugging

---

rootdir/fstab.loire

/dev/block/bootdevice/by-name/FOTAKernel -> /dev/block/mmcblk0p32

Loire: use correct path for recovery partition

---

system.prop

Adjust for hexcore SoC
make little cores easy to online
make big cores difficult to online

cpuquiet: tune hotplugging for loire platform

---

PlatformConfig.mk

07249f04fb66549fc745140d0d9ebef8179eaed6 has been merged and we
no longer need the external BT patches
Change-Id: Ie97958491741d346c0f49bf4fe8aa0ad86cf27ec

loire: fix BT customisation

---

rootdir/system/etc/media_codecs.xml

let this as base for M and N following Nexus Devices

loire: remove unused codecs in AOSP

---

bluetooth/bdroid_buildcfg.h

Use ro.boot.hardware property for BT device name.
The OS_GENERIC flag is required due to this:
https://android.googlesource.com/platform/system/bt/+/android-7.0.0_r1/osi/Android.mk#147
https://android.googlesource.com/platform/system/bt/+/android-7.0.0_r1/osi/include/properties.h#21

[master] sony: loire: Reintroduce BT device name

---

system.prop

RQBalance has a special management algorithm for HMP SoC
which manages BIG cores sligthly differently from LITTLE
ones.
When we try to up 4 LITTLE cores, it will instead upcore
2 LITTLE and one BIG, since the computational power of
the BIG ones is more than 2x the LITTLEs.
It will then upcore one more LITTLE if computational power
is still not enough.
Setting the min cores to a number that is equal to MAX
of LITTLE cluster cores, we are breaking this behavior
resulting in a less efficient and not (power)linear
up/downcore management, hence, the minimum cores to make
the mechanism to work efficiently is 2 on Kitakami (MSM8994).

loire: Tune rqbalance for linear core scaling in normal

---

platform.mk

This patch increases dex2oat threads to 4 for faster app installation.

sony: loire: Optimal dex2oat threads for faster app installation

---

rootdir/fstab.loire

Android Nougat changed how it communicates with the recovery
partition. Until now the recovery commands had been written
to the /cache partition, but this has changed. Now recovery
writes to the /misc partition.
Fortunately for loire devices we actually have
an empty and unused /apps_log partition we can use.

fstab: Allow recovery to use the misc partition

---

rootdir/fstab.loire
rootdir/init.loire.rc

This can give a nice performance boost under heavy load
Needs the ZRAM driver upgrade: https://github.com/sonyxperiadev/kernel/pull/895

Configure Zram on loire devices

---

rootdir/init.loire.rc

1. Set lz4 as default compression algorithm.
2. Increase max_comp_streams from 1 to 4
Regardless the value passed to this attribute, ZRAM will always
allocate multiple compression streams - one per online CPUs - thus
allowing several concurrent compression operations. The number of
allocated compression streams goes down when some of the CPUs
become offline. There is no single-compression-stream mode anymore,
unless you are running a UP system or has only 1 CPU online
3. Set page-cluster to 0 (zero). This means "1 page".
Also, zero disables swap readahead completely.
Page-cluster controls the number of pages up to which consecutive pages
are read in from swap in a single attempt. This is the swap counterpart
to page cache readahead.
The mentioned consecutivity is not in terms of …

[master] sony: loire: Add zram options

---

rootdir/init.loire.rc

this is needed in order to let macaddrsetup into which file it should
write the wifi mac address.

init: add wifi mac address path to macaddrsetup

---

rootdir/init.loire.rc

Write the bluetooth macaddr to a place that is natively readable
by bluetooth services, instead of creating new locations which
requires excessive permissions.

macaddr: remove dangerous sepolicy permissions

---

rootdir/init.loire.rc
rootdir/system/etc/bluetooth/bt_vendor.conf
rootdir/ueventd.loire.rc

Those patches are logically required for BRCM BT FM.
To do: check the correct /dev/radio0 permission

BRCM BT FM

---

rootdir/init.loire.rc

It is required for sepolicy.
Change-Id: Ib21b3608f3e6d696be14b11dbd8286e49d23acdb

sony: loire: init: Label UIM service

---

rootdir/init.loire.rc

For some reason the fs_mgr is showing the mount error for zram (swap).
[   13.402500] fs_mgr: mkswap failed for /dev/block/zram0
So, move the swap mount process to "on post-fs" stage and get it fixed.
[   13.810523] Adding 524284k swap on /dev/block/zram0.  Priority:-1 extents:1 across:524284k SS
Change-Id: Ifbf55344e3ebb0f161f8c5ced621e720661b53ba

sony: loire: Fix swap mount process

---

rootdir/init.loire.rc

it is required on 3.18 kernel.
Change-Id: I7b27f069ab8f90d6b4b61eb475e1d327b5c5b31e

[master] sony: loire: init: Fix macaddress sysfs

---

PlatformConfig.mk
platform.mk

* Avoid hardcoding the paths by using common
variables declared once for path accesses
Change-Id: I81226a249c6258360c540c80ae4dfe5073439921
Signed-off-by: Adrian DC <radian.dc@gmail.com>

loire: config: Use unique variables for device paths

---

PlatformConfig.mk

It is expected from sdhci driver@3.18.

[master] sony: loire: Add androidboot.bootdevice to cmdline

---

PlatformConfig.mk

following marling config https://android.googlesource.com/device/google/marlin/+/android-7.1.1_r8/marlin/BoardConfig.mk#200

loire: use correct flag nfc for android-7.1.1

---

rootdir/system/etc/audio_platform_info.xml

PCM_OFFLOAD is currently not supported by aosp and it's CAF
02-01 23:28:42.062   455   455 E platform_info: process_pcm_id: usecase USECASE_AUDIO_PLAYBACK_OFFLOAD2 in /system/etc/audio_platform_info.xml not found!
02-01 23:28:42.062   455   455 E platform_info: process_pcm_id: usecase USECASE_AUDIO_PLAYBACK_OFFLOAD3 in /system/etc/audio_platform_info.xml not found!
02-01 23:28:42.062   455   455 E platform_info: process_pcm_id: usecase USECASE_AUDIO_PLAYBACK_OFFLOAD4 in /system/etc/audio_platform_info.xml not found!
02-01 23:28:42.062   455   455 E platform_info: process_pcm_id: usecase USECASE_AUDIO_PLAYBACK_OFFLOAD5 in /system/etc/audio_platform_info.xml not found!
02-01 23:28:42.062   455   455 E platform_info: process_pcm_id: usecase USECASE_AUDIO_PLAYBACK_OFFLOAD6 in …

loire: audio: remove PCM_OFFLOAD ids

---

rootdir/system/etc/audio_platform_info.xml

correct audio_platform_info for msm8952 tomtom and 8976 tasha sound cards are audio_platform_info_extcodec.xml
see 8952 caf implementation https://source.codeaurora.org/quic/la/platform/hardware/qcom/audio/diff/?h=LA.BR.1.3.3_rb2.14&id=0d28b4a9c06b8f6f9647bfe3e6ff24a38fd52432
see 8976 caf implementation https://source.codeaurora.org/quic/la/platform/hardware/qcom/audio/diff/?h=LA.BR.1.3.3_rb2.14&id=d7691747054a99583e1d4225d37eb631fdb2eceb
both 8952 and 8976 use external_codec

loire: fix audio in call

---

rootdir/init.loire.rc

needed after recent DT changes in kernel for loire

loire: fix macaddr path

---

bluetooth/bdroid_buildcfg.h
rootdir/system/etc/bluetooth/bt_vendor.conf

Please see sonyxperiadev/kernel#1162
This is the required user space modification (2/2) for combined BT/FMRadio support via the broadcom ldisc driver.

[WIP - n-mr1] BT/FMRadio using the broadcom ldisc driver

---

bluetooth/bdroid_buildcfg.h
rootdir/system/etc/bluetooth/bt_vendor.conf

Please see sonyxperiadev/kernel#1162
This is the required user space modification (2/2) for combined BT/FMRadio support via the broadcom ldisc driver.

[WIP - n-mr0] BT/FMRadio using the broadcom ldisc driver

---

bluetooth/bdroid_buildcfg.h
rootdir/system/etc/bluetooth/bt_vendor.conf

Please see sonyxperiadev/kernel#1162
This is the required user space modification (2/2) for combined BT/FMRadio support via the broadcom ldisc driver.

[WIP - m-mr1] BT/FMRadio using the broadcom ldisc driver

---

bluetooth/bdroid_buildcfg.h

Move HCILP_INCLUDED out of OS_GENERIC #ifdef .
OS_GENERIC flag was used to fix BTDefaultName at Nougat.
Change-Id: Ie12227b649ff087a5ceba955b47d8b84f82706ac

sony: loire: Move BT flag

---

bluetooth/bdroid_buildcfg.h
rootdir/system/etc/bluetooth/bt_vendor.conf

- UartPort is evaluated by libbt (pass BT data to the brcm ldisc driver).
UimUartPort is evaluated by the uim service which needs to be aware of
the uart device node to which the ldisc driver is attached.
Naming aligned with Ie185dcc8aa965b2d4df7dea26adbcc1036c38c6a
- Disable power state handling by libbt as it is done in the brcm driver.
Change-Id: Ifddbc4e3867a62f821a0081312ec441fbe390c49
Signed-off-by: Alexander Diewald <Diewi@diewald-net.com>

Adjust device nodes for the brcm BT/FMRadio driver & power handling

---

rootdir/system/etc/audio_platform_info.xml

On stock, the device SND_DEVICE_OUT_VOICE_SPEAKER_WSA is the actual incall speaker,
which is calibrated using acdb.
Since that device has a different acdb_id than SND_DEVICE_OUT_VOICE_SPEAKER, this
causes calibration to fail on AOSP, when using .acdb files from stock. This is due to
that acdb_id mismatch
Fix it by mapping SND_DEVICE_OUT_VOICE_SPEAKER on AOSP to the same acdb_id.
Change-Id: I735d649397c5364aa757462462a8f296e638f9d0

[Master] [WELCOME LOUDNESS] rootdir: audio: add acdb_id mapping for incall speaker

---

rootdir/system/etc/audio_platform_info.xml

On stock, the device SND_DEVICE_OUT_VOICE_SPEAKER_WSA is the actual incall speaker,
which is calibrated using acdb.
Since that device has a different acdb_id than SND_DEVICE_OUT_VOICE_SPEAKER, this
causes calibration to fail on AOSP, when using .acdb files from stock. This is due to
that acdb_id mismatch
Fix it by mapping SND_DEVICE_OUT_VOICE_SPEAKER on AOSP to the same acdb_id.
Change-Id: I735d649397c5364aa757462462a8f296e638f9d0

[N-MR1] rootdir: audio: add acdb_id mapping for incall speaker

---

rootdir/system/etc/audio_platform_info.xml

On stock, the device SND_DEVICE_OUT_VOICE_SPEAKER_WSA is the actual incall speaker,
which is calibrated using acdb.
Since that device has a different acdb_id than SND_DEVICE_OUT_VOICE_SPEAKER, this
causes calibration to fail on AOSP, when using .acdb files from stock. This is due to
that acdb_id mismatch
Fix it by mapping SND_DEVICE_OUT_VOICE_SPEAKER on AOSP to the same acdb_id.
Change-Id: I735d649397c5364aa757462462a8f296e638f9d0

[M-MR1] rootdir: audio: add acdb_id mapping for incall speaker

---

rootdir/system/etc/audio_platform_info.xml

On stock, the device SND_DEVICE_OUT_VOICE_SPEAKER_WSA is the actual incall speaker,
which is calibrated using acdb.
Since that device has a different acdb_id than SND_DEVICE_OUT_VOICE_SPEAKER, this
causes calibration to fail on AOSP, when using .acdb files from stock. This is due to
that acdb_id mismatch
Fix it by mapping SND_DEVICE_OUT_VOICE_SPEAKER on AOSP to the same acdb_id.
Change-Id: I735d649397c5364aa757462462a8f296e638f9d0

[N-MR0] rootdir: audio: add acdb_id mapping for incall speaker

---

rootdir/system/etc/audio_platform_info.xml

Speaker configuration parameters were wrong as AOSP
HAL wants the config_params node.
ACDB IDs were also missed and wrong.
Old pcm_ids now do apply, as the AOSP HAL also can
understand USECASE_AUDIO_SPKR_CALIB_TX.

[LOIRE] Audio: New ACDB IDs and right parameters

---

rootdir/system/etc/audio_platform_info.xml

Speaker configuration parameters were wrong as AOSP
HAL wants the config_params node.
ACDB IDs were also missed and wrong.
Old pcm_ids now do apply, as the AOSP HAL also can
understand USECASE_AUDIO_SPKR_CALIB_TX.

[LOIRE n-mr1] Audio: New ACDB IDs and right parameters

---

rootdir/fstab.loire

Loire platform needs the DSP partition for the QC
FastRPC daemon to work correctly.

[LOIRE] fstab: Add DSP partition for mount

---

rootdir/fstab.loire

Loire platform needs the DSP partition for the QC
FastRPC daemon to work correctly.

[LOIRE n-mr1] fstab: Add DSP partition for mount

---

sepolicy_platform/file_contexts

It is requires for acdb.
Change-Id: Icce0e24ff08988aaca1de3d61d02aa992eb3f431

[master] sony: loire: sepolicy: Add dsp device to file contexts

---

sepolicy_platform/file_contexts

on kernel 3.10 dev block nodes are soc.0 not soc

loire: fix block nodes for kernel 3.10

---

rootdir/init.loire.rc

Regardless the value passed to this attribute, ZRAM will always
allocate multiple compression streams - one per online CPUs - thus
allowing several concurrent compression operations. The number of
allocated compression streams goes down when some of the CPUs
become offline. There is no single-compression-stream mode anymore,
unless you are running a UP system or has only 1 CPU online.
Change-Id: I8ff3fef28d48aec1715be687d961cb11628dab53

[master] sony: loire: Increase max number of compression streams

---

rootdir/init.loire.rc

Regardless the value passed to this attribute, ZRAM will always
allocate multiple compression streams - one per online CPUs - thus
allowing several concurrent compression operations. The number of
allocated compression streams goes down when some of the CPUs
become offline. There is no single-compression-stream mode anymore,
unless you are running a UP system or has only 1 CPU online.
Change-Id: I8ff3fef28d48aec1715be687d961cb11628dab53

sony: loire: Increase max number of compression streams

---

rootdir/ueventd.loire.rc

lrwxrwxrwx 1 root root 0 2017-08-14 09:32 wled:backlight -> ../../devices/soc/200f000.qcom,spmi/spmi-0/spmi0-03/200f000.qcom,spmi:qcom,pmi8950@3:qcom,leds@d800/leds/wled:backlight

loire: fix wled:backlight path

---

platform.mk
rootdir/system/etc/p2p_supplicant_overlay.conf
rootdir/system/etc/wpa_supplicant_overlay.conf

loire needs customized overlays to remove wowlan, which causes device to crash randomly while booting.
This is based on the same modifications done for tone
https://github.com/sonyxperiadev/device-sony-tone/commit/65d4ec3315ecfae662f16e82b020567da69c7a0a

loire: wifi: use platform specific wpa and p2p overlays

---

rootdir/init.recovery.loire.rc

following https://github.com/sonyxperiadev/device-sony-tone/commit/6196fb892b9ab721e784c58023e724ce5d1bc00b

loire: Configure recovery for USB ConfigFS

---

rootdir/init.loire.rc

Android can not write fw to the sysfs node due to missing permissions:
E android.hardware.wifi@1.0-service: Failed to open wlan fw path param: Permission denied
By setting the user to wifi, fw can be written and wifi starts properly.
Also, fix a small comment issue where wifi related command was annotated by Bluetooth.

rootdir: init: set wifi user for bcmdhd firmware path

---

rootdir/init.loire.rc

daemon fingerprint is not more on android oreo it was replaced by android.hardware.biometrics.fingerprint

loire: remove not needed fingerprint service

---

overlay/frameworks/base/core/res/res/values/config.xml

.vdex files have been added to allow pre-verified dex.  The pinner
service needs to take this in account when pinning.  Add pinning of
appropriate system .vdex files on device.
Bug 33168521
Test:  Tested manually by confirming pinning is successful
Change-Id: Ice2c3f0ec0b314963fb136793d9fa36ecba58490

Pin .vdex files as well

---

rootdir/system/etc/media_codecs.xml

These codecs are proprietary and we don't want to use it.
OSS is the way.

[LOIRE] [V2] media: Remove proprietary codecs support

---

platform.mk
rootdir/system/etc/p2p_supplicant_overlay.conf
rootdir/system/etc/wpa_supplicant_overlay.conf

Since kernel was fixed (bcmdhd driver) this overlay is not necessary.
Signed-off-by: Humberto Borba <humberos@omnirom.org>
Change-Id: If762a54709022cc23655b6e13c0bbd6977723799

[master] sony: loire: Add aosp wpa/p2p overlay back

---

platform.mk
rootdir/system/etc/p2p_supplicant_overlay.conf
rootdir/system/etc/wpa_supplicant_overlay.conf

Since kernel was fixed (bcmdhd driver) this overlay is not necessary.
Signed-off-by: Humberto Borba <humberos@omnirom.org>
Change-Id: If762a54709022cc23655b6e13c0bbd6977723799

[n-mr1] sony: loire: Add aosp wpa/p2p overlay back

---

platform.mk

needed for USB tethering usecase

loire: add sys.usb.rndis.func.name prop

---

rootdir/system/etc/audio_platform_info.xml

based on CAF https://source.codeaurora.org/quic/la/platform/hardware/qcom/audio/tree/configs/msm8952_32/audio_platform_info_extcodec.xml?h=LA.BR.1.3.7_rb1.3

loire: update audio_platform_info.xml

---

sepolicy_platform/file_contexts

This is used by the common rdclean.sh rules, see device/sony/common
for the details.
Signed-off-by: Oleksiy Avramchenko <oleksiy.avramchenko@sony.com>

loire: label ramdump partition

---

rootdir/system/etc/media_codecs_performance.xml

The typo made the measured-frame-rate-640x380 for VP8 encoder
to not get recognized, due to bad range specification.

[LOIRE] media_codecs_performance: Fix typo

---

platform.mk

MSM8956 Venus does not support UBWC. Make sure it never gets
enabled.
----------------------
Tested on Suzu. Fixes the weird Instagram issue.

[LOIRE] Add properties to avoid UBWC buffers on VENC

---

rootdir/ueventd.loire.rc

Add /dev/fingerprint perms for the new IOCTL implementation.

[LOIRE] ueventd: Fix for FPC IOCTL implementation

---

rootdir/init.loire.rc

There is a symlink from /vendor to /system/vendor.

loire: Fix service path for Android O

---

rootdir/init.loire.rc

Camera daemon is no longer used so it makes no sense to reserve
CPU 3 for the camera daemon.

[o-mr0] init.loire.rc: Do not reserve CPU 3 for the camera daemon

---

rootdir/init.loire.rc

Camera daemon is no longer used so it makes no sense to reserve
CPU 3 for the camera daemon.

[master] init.loire.rc: Do not reserve CPU 3 for the camera daemon

---

platform.mk

Vulkan is not supported on 8952
Set "persist.graphics.vulkan.disable" for Soc_id 264 to true.
Framework checks for this flag and disables
Vulkan features for 8952.
Signed-off-by: Humberto Borba <humberos@omnirom.org>
Change-Id: I32c42d0ca488b22c3a3cac96044bdf6356535c11

[master] sony: loire: graphics: Disable Vulkan for 8952

---

platform.mk

This is required for the media HAL to respect MSM8956
features, such as declaring the correct AVC Level 5.1 and
disabling the unsupported intra-refresh mode for MPEG4.

[LOIRE] platform: Use MSM8956 featureset for vidc encoders

---

platform.mk

This patch was for MSM8952 and loire is MSM8956
So it is a mistake.
Thanks to @oshmoun for reviewing this.
This reverts commit 5d6c6cf36300b5f3e201dd2bc9dcc213ad92cbff.
Change-Id: I772545d0e2269e28719ef3f60b81319c29057f46

[master] Revert "sony: loire: graphics: Disable Vulkan for 8952"

---

rootdir/fstab.loire

it changed from /devices/platform/msm_hsusb_host/usb* to /devices/soc/78db000.usb/msm_hsusb_host/usb*

loire: fix otg path

---

rootdir/fstab.loire

After the removal of the mount for system, the build system failed to generate OTA packages, as it relies on fstab to know what to mount when executing the update script.
This reverts the removal of the lines, and adds to them the flag "recoveryonly" to avoid having Android attempt a remount of those partitions.

fix generation of OTA packages

---

rootdir/fstab.loire

After the removal of the mount for system, the build system failed to generate OTA packages, as it relies on fstab to know what to mount when executing the update script.
This reverts the removal of the lines, and adds to them the flag "recoveryonly" to avoid having Android attempt a remount of those partitions.

[o-mr0] fix generation of OTA packages

---

rootdir/vendor/usr/idc/clearpad.idc

Changes introduced in Android 8.1.0 produced a miscalculation
of the touch pressure axis.
Change the touch pressure scale to 0.01 to prevent overflowing
and get back the touch pressure working properly, solving issues
with multi-touch gestures in various games.
Also, while at it, make sure that the device is declared as internal,
orientation aware and that the touch pressure parameter is read
from the "pressure axis" sent by the kernel driver.

[LOIRE] vendor: IDC: clearpad: Fix touch pressure issues and cleanup

---

rootdir/vendor/etc/init/init.loire.pwr.rc

The frequencies supported by cpufreq have changed in kernel, so reflect the changes here.

rootdir: vendor: Adjust minimum frequencies and touch boost

---

PlatformConfig.mk

Allow overriding TARGET_RECOVERY_FSTAB

---

rootdir/vendor/etc/fstab.loire

On kernel 4.9, /sys/devices/soc has been moved
to /sys/devices/platform/soc.

[master] fstab: Update paths for k4.9

---

bluetooth/bdroid_buildcfg.h

without this /system/bt gives errors in build like Already defined in ./bionic/libc/include/sys/system_properties.h

bt: fix error in build

---

PlatformConfig.mk

brcmfmac uses the kernel's firmware API to get what it needs.
Do not declare any fw paths in that case to avoid wifi hal failure.

PlatformConfig: declare fw paths only if brcmfmac is not used

---

platform.mk
rootdir/vendor/etc/init/init.loire.rc
rootdir/vendor/ueventd.rc
sepolicy_platform/genfs_contexts

On kernel 4.9, /sys/devices/soc has been moved
to /sys/devices/platform/soc.
This branch for Android P+ and it uses kernel 4.9 only.

[master] Remove deprecated paths

---

PlatformConfig.mk

This platform uses old Adreno binaries and is not compatible
with the new style gralloc.

[LOIRE] PlatformConfig: Define TARGET_USES_GRALLOC1 for legacy

---

sepolicy_platform/genfs_contexts

following qcom platforms and aosp sepolicy
https://android.googlesource.com/platform/system/sepolicy/+/android-9.0.0_r21/public/file.te#82
https://android.googlesource.com/platform/system/sepolicy/+/android-9.0.0_r21/private/priv_app.te#90
avoid
12-31 23:06:13.548  5269  5269 I Binder:5269_3: type=1400 audit(0.0:88): avc: denied { open } for path=/sys/devices/platform/soc/7a24900.sdhci/mmc_host/mmc2/mmc2:0001/mmc2:0001:1/net/wlan0/address dev=sysfs ino=44026 scontext=u:r:priv_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=1
12-31 23:06:13.548  5269  5269 I Binder:5269_3: type=1400 audit(0.0:89): avc: denied { getattr } for path=/sys/devices/platform/soc/7a24900.sdhci/mmc_host/mmc2/mmc2:0001/mmc2:0001:1/net/wlan0/address dev=sysfs ino=44026 …

label 7a24900.sdhci/mmc_host/mmc2/mmc2:0001/mmc2:0001:1/net as sysfs_net

---

rootdir/vendor/etc/fstab.loire

Since there is no longer a command in init.common.rc that remounts as read-only, set the property directly in fstab.

[loire] fstab: Mount dsp partition read-only

---

rootdir/vendor/etc/init/init.loire.rc

Loire devices will crash randomly on boot in the current setup.
After some testing, seems the issue is resolved by delaying the start of hwcomposer service.
The cause of the crash is not identified. This is just an ugly workaround till the cause is found.

[HACK] rootdir: vendor: init: delay start of hwcomposer

---

sepolicy_platform/genfs_contexts

Now all the symlinks from /sys/class/power_supply/* should be labeled for loire.
android.hardwar: type=1400 audit(0.0:5): avc: denied { getattr } for \
path="/sys/devices/platform/soc/200f000.qcom,spmi/spmi-0/spmi0-02/200f000.qcom,spmi:qcom,pmi8950@2:bcl@4200/power_supply/fg_adc/type" \
dev="sysfs" ino=36739 scontext=u:r:hal_health_default:s0 tcontext=u:object_r:sysfs_msm_subsys:s0 tclass=file permissive=1

[WIP] sepolicy_platform: Missing power supply paths

---

PlatformConfig.mk

bcmdhd implementation relies on custom ioctls that are not supported by the mainline brcmfmac driver.
qcwcn libs is closer to the standard interfaces, and hence actually more compatible than bcmdhd libs.
also remove the declaration of firmware paths if bcmdhd is used, since it is now compeletely superceded by brcmfmac and will not be considered again.

PlatformConfig: switch wifi libs to qcwcn from bcmdhd

---

platform.mk

Loading the extension library fails because it can not find libscalar.so, which is indeed not provided.
This leads to failure when initializing the display hal.
Since the extension interface is not critically required on loire, skip it.

platform: add property to skip loading libsdmextension

---

platform.mk

The `KERNEL_PATH` buildvar needs to be set before `common.mk` can be inherited.

[FIX] platform.mk: Define kernel vars before common.mk

---

platform.mk
rootdir/vendor/etc/libnfc-nci.conf

All loire devices share the `PN547C2` chip and the NCI config can be unified
This change also moves the files from `/system/etc` to `/vendor/etc` for treble compliance.

Move libnfc-nci.conf to loire shared

---

rootdir/vendor/etc/init/init.loire.rc

Limit MTP_RX_BUFFER_INIT_SIZE and MTP_TX_BUFFER_INIT_SIZE from 1048576 to 16384
Should fix swiotlb running OOM with large file transfers.
See https://github.com/sonyxperiadev/bug_tracker/issues/432#issuecomment-517964636
Needs accompanying sepolicy.

[VERIFYME] init: Limit MTP rx/tx buffers to 16384

---

PlatformConfig.mk

This reverts commit 2d5a63e4cb02e8ecf26bbddd6cd7f7a1f863858d.
TARGET_LEGACY_KEYMASTER flag already defined
in PlatformConfig.mk.

[master] Revert "declare TARGET_LEGACY_KEYMASTER"

---

platform.mk

According to display HAL updates, all the properties
received prefixes vendor.display. or vendor.gralloc.,
depending on which part they belong to, so update all
properties accordingly.

[master] platform: Update display property names

---

platform.mk

This reverts commit 01cdb1528f4aaba6d9100c4a4d650e557ea11c06.
Reason for revert: 4.14 does not boot on loire at the moment.
Devices have been moved to the android-10_legacy branch and stay on Kernel 4.9.

Revert "move msm8956 devices to kernel 4.14"

---

platform.mk
rootdir/vendor/etc/audio_policy_configuration.xml
rootdir/vendor/etc/audio_policy_configuration_bluetooth_legacy_hal.xml
rootdir/vendor/etc/common_primary_audio_policy_configuration.xml

The audio.bluetooth.default.so audio module, configured by
bluetooth_audio_policy_configuration.xml, utilizes the new HAL-based
mechanism to register a BT audio endpoint and transfer audio data.
Update our policy to route audio properly to this module, while
retaining a2dp input compatibility through the old mechanism.
See the identical change in crosshatch:
https://android.googlesource.com/device/google/crosshatch/+/c05ccdbed6c7c74d450e7149969c6c3431155628
audio_policy_configuration_bluetooth_legacy_hal.xml remains unchanged to
reflect the old variant of the system (using sockets between the BT
stack and audioserver), usable with
persist.bluetooth.bluetooth_audio_hal.disabled=true.
NOTE: This relies on device-sony-common to add the new files to
PRODUCT_COPY_FILES.

[LOIRE] audio_policy: Migrate to bluetooth.audio@2.0 HAL policy

---

rootdir/vendor/etc/fstab.loire

**VERIFY ME!** Calling @oshmoun and other loire owners.
Makes things neater with the stage-separated mounting logic in Q and later.

fstab: Split into early and latemount, reserve 128M on /data

---

sepolicy_platform/genfs_contexts

Needed for the health HAL to extract storage health and statistics.
See https://github.com/sonyxperiadev/device-sony-common/pull/628 and https://github.com/sonyxperiadev/device-sony-sepolicy/pull/530

[WIP] sepolicy_platform: Label sdhci MMC node
